### PR TITLE
retireve everything in LruCache

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/dirvine/lru_time_cache/9)

### CODE REVIEW

**Comment by chandraprakash** [comment]
good to go .. @rossmuir  can u confirm it builds ?

**Comment by rossmuir** [comment]
@chandraprakash it is building on beta > https://travis-ci.org/dirvine/lru_time_cache/jobs/59726794

**Comment by chandraprakash** [comment]
@dirvine  this can be merged

**Comment by dirvine** [comment]
Reviewed files:
- src/lib.rs @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dirvine/lru_time_cache/9)

**Pull request merged**
